#! /bin/bash

COMPILER_RUNTIME=/Users/liufengyun/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.8.jar:/Users/liufengyun/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.8.jar:/Users/liufengyun/.ivy2/cache/org.scala-sbt/interface/jars/interface-0.13.9.jar:/Users/liufengyun/Documents/scala/target/scala-2.11/scala_2.11-0.1-SNAPSHOT.jar

LIB=.:/Users/liufengyun/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.5.jar:/Users/liufengyun/Documents/dotty/target/scala-2.11/dotty_2.11-0.1-SNAPSHOT.jar:/Users/liufengyun/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.5.jar:/Users/liufengyun/.ivy2/cache/org.scala-lang/scala-xml/jars/scala-xml-2.11.0-M4.jar

# compile user program
java -cp $COMPILER_RUNTIME dotty.tools.dotc.Main -classpath $LIB "$@"

